name: gratitude_diary
description: "Reflect, Record, Rejoice"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  encrypt: ^5.0.3
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loading_animation_widget: 1.2.1
  logger: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  spider: ^4.2.2
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:

  uses-material-design: true

  assets:
    - asset/image/google.jpg
    - .env
