// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGp-pi3Nttn7ee6ghzRudObAyawDjzOmU',
    appId: '1:853604883721:web:b9c14b16c8f4d4959787d8',
    messagingSenderId: '853604883721',
    projectId: 'gratitude-diary-58e2e',
    authDomain: 'gratitude-diary-58e2e.firebaseapp.com',
    storageBucket: 'gratitude-diary-58e2e.appspot.com',
    measurementId: 'G-CMJXL5WCW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWg0sKrnmVXnsLbCrnO8_ljf2PBn1fJA',
    appId: '1:853604883721:android:576db09173ae8d859787d8',
    messagingSenderId: '853604883721',
    projectId: 'gratitude-diary-58e2e',
    storageBucket: 'gratitude-diary-58e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaMBbRZOiud8NPJfR5kzrRqTFGda6tQo',
    appId: '1:853604883721:ios:6ece3d3ffc1c5af39787d8',
    messagingSenderId: '853604883721',
    projectId: 'gratitude-diary-58e2e',
    storageBucket: 'gratitude-diary-58e2e.appspot.com',
    iosClientId: '853604883721-808i15k3iqbmq2of6o45urkeerlv2ail.apps.googleusercontent.com',
    iosBundleId: 'com.example.gratitudeDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPaMBbRZOiud8NPJfR5kzrRqTFGda6tQo',
    appId: '1:853604883721:ios:6ece3d3ffc1c5af39787d8',
    messagingSenderId: '853604883721',
    projectId: 'gratitude-diary-58e2e',
    storageBucket: 'gratitude-diary-58e2e.appspot.com',
    iosClientId: '853604883721-808i15k3iqbmq2of6o45urkeerlv2ail.apps.googleusercontent.com',
    iosBundleId: 'com.example.gratitudeDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGp-pi3Nttn7ee6ghzRudObAyawDjzOmU',
    appId: '1:853604883721:web:606eb242186393b49787d8',
    messagingSenderId: '853604883721',
    projectId: 'gratitude-diary-58e2e',
    authDomain: 'gratitude-diary-58e2e.firebaseapp.com',
    storageBucket: 'gratitude-diary-58e2e.appspot.com',
    measurementId: 'G-6ZGQD2EM73',
  );

}